version: '3.7'

networks:
  app-net:

services:
  db:
    image: postgres:11.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - app-net
    ports:
      - "5432:5432"